device_management:
    path:     /device_management
    defaults: { _controller: CEDeviceBundle:Default:index }

device_create:
    path:     /device_create
    defaults: { _controller: CEDeviceBundle:Default:create }

device_edit:
    path:     /device_edit/{id}
    defaults: { _controller: CEDeviceBundle:Default:edit }
    requirements:
        id: \d+